# This rule is not used by the project op-cron-scale itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the op-cron-scale.op-cron-scale.example.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: op-cron-scale
    app.kubernetes.io/managed-by: kustomize
  name: CronScaler-editor-role
rules:
- apiGroups:
  - op-cron-scale.op-cron-scale.example.com
  resources:
  - cronscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - op-cron-scale.op-cron-scale.example.com
  resources:
  - cronscalers/status
  verbs:
  - get
