---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - op-cron-scale.op-cron-scale.example.com
  resources:
  - cronscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - op-cron-scale.op-cron-scale.example.com
  resources:
  - cronscalers/finalizers
  verbs:
  - update
- apiGroups:
  - op-cron-scale.op-cron-scale.example.com
  resources:
  - cronscalers/status
  verbs:
  - get
  - patch
  - update
